[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "tarzi"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
version = "0.0.3"
description = "Rust-native lite search for AI applications"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "xmingc", email = "chenxm35@gmail.com"},
]

[project.urls]
Homepage = "https://github.com/mirasurf/tarzi"
Repository = "https://github.com/mirasurf/tarzi"

[tool.maturin]
features = ["pyo3/extension-module"] 