[general]
log_level = "info"
timeout = 30

[fetcher]
mode = "browser_headless"
format = "markdown"
user_agent = "Mozilla/5.0 (compatible; Tarzi/1.0)"
# user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
timeout = 30
proxy = "http://127.0.0.1:7890"
chromedriver_port = 4444

[search]
mode = "webquery"
engine = "bing"
query_pattern = "https://www.bing.com/search?q={query}"
limit = 5
api_key = "your-api-key-for-apiquery-mode"
