[general]
log_level = "info"
timeout = 30

[fetcher]
mode = "browser_headless"
format = "markdown"
user_agent = "Mozilla/5.0 (compatible; Tarzi/1.0)"
timeout = 30
proxy = "http://127.0.0.1:7890"

[search]
mode = "webquery"
engine = "bing"
query_pattern = "https://www.bing.com/search?q={query}"
limit = 5
api_key = "your-api-key-for-apiquery-mode"
