[general]
log_level = "info"
timeout = 30

[fetcher]
mode = "browser_headless"
format = "markdown"
# proxy = "http://127.0.0.1:7890"
web_driver = "chromedriver" # geckodriver
web_driver_port = 9515

[search]
mode = "webquery"
engine = "bing"
query_pattern = "https://www.bing.com/search?q={query}"
limit = 5
api_key = "your-api-key-for-apiquery-mode"
