name: Publish Packages

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to publish to'
        required: true
        default: 'testpypi'
        type: choice
        options:
        - testpypi
        - pypi
      dry_run:
        description: 'Dry run - only build, no publishing'
        required: false
        default: false
        type: boolean

jobs:
  build-macos-wheels:
    name: Build wheels on ${{ matrix.os }} (${{ matrix.arch }}) for Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ['3.10', '3.11', '3.12']
        arch: [x64, arm64]
        include:
          # macOS runners - use macos-13 for x64, macos-latest for arm64
          - os: macos-latest
            arch: x64
            runner: macos-13
          - os: macos-latest
            arch: arm64
            runner: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} (${{ matrix.arch }})
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ matrix.runner }}-${{ matrix.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ matrix.runner }}-${{ matrix.arch }}-cargo-
    
    - name: Install maturin
      run: pip install maturin[patchelf]
    
    - name: Build wheels
      run: maturin build --release --out dist --interpreter python${{ matrix.python-version }}
    
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.arch }}-py${{ matrix.python-version }}
        path: dist

  build-linux-wheels:
    name: Build manylinux wheels for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        arch: [x64, arm64]
        include:
          - arch: x64
            manylinux: manylinux2014
            platform: x86_64
          - arch: arm64
            manylinux: manylinux2014
            platform: aarch64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v2.16.2
      env:
        OPENSSL_DIR: /usr/local
        PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
        OPENSSL_LIB_DIR: /usr/local/lib
        OPENSSL_INCLUDE_DIR: /usr/local/include
        RUSTUP_HOME: /usr/local/rustup
        CARGO_HOME: /usr/local/cargo
        PATH: /usr/local/cargo/bin:$PATH
      with:
        platform: linux
        archs: ${{ matrix.arch }}
        python-versions: ${{ matrix.python-version }}
        build-verbosity: 1
        output-dir: dist
        repair-wheel-command: |
          python -m pip install auditwheel
          auditwheel repair --plat {platform} -w {dest_dir} {wheel}
        before-all: |
          # Install OpenSSL development packages
          yum install -y openssl-devel libssl-dev
          # Install Rust
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          source $HOME/.cargo/env
          # Set OpenSSL environment variables
          export OPENSSL_DIR=/usr/local
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
          export OPENSSL_LIB_DIR=/usr/local/lib
          export OPENSSL_INCLUDE_DIR=/usr/local/include
          # Ensure Rust is in PATH
          export PATH=$HOME/.cargo/bin:$PATH
    
    - name: Upload manylinux wheels
      uses: actions/upload-artifact@v4
      with:
        name: manylinux-wheels-${{ matrix.arch }}-py${{ matrix.python-version }}
        path: dist

  publish-python:
    name: Publish Python Package
    runs-on: ubuntu-latest
    needs: [build-macos-wheels, build-linux-wheels]
    if: >
      github.event_name == 'release' || 
      (github.event_name == 'workflow_dispatch' && (!github.event.inputs.dry_run || github.event.inputs.dry_run == 'false'))
    environment: ${{ github.event.inputs.environment || 'pypi' }}
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all wheels
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Collect wheels
      run: |
        mkdir -p dist
        find artifacts -name "*.whl" -exec cp {} dist/ \;
        find artifacts -name "*.tar.gz" -exec cp {} dist/ \;
        ls -la dist/
    
    - name: Publish to TestPyPI
      if: github.event.inputs.environment == 'testpypi' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'testpypi')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
    
    - name: Publish to PyPI
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-rust:
    name: Publish Rust Crate
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'release' || 
      (github.event_name == 'workflow_dispatch' && (!github.event.inputs.dry_run || github.event.inputs.dry_run == 'false'))
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish

  dry-run-summary:
    name: Dry Run Summary
    runs-on: ubuntu-latest
    needs: [build-macos-wheels, build-linux-wheels]
    if: ${{ github.event.inputs.dry_run == 'true' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all wheels
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Show built artifacts
      run: |
        echo "=== DRY RUN SUMMARY ==="
        echo "Built wheels and source distributions:"
        find artifacts -name "*.whl" -o -name "*.tar.gz" | sort
        echo ""
        echo "Total artifacts:"
        find artifacts -name "*.whl" -o -name "*.tar.gz" | wc -l
        echo ""
        echo "Wheel types:"
        echo "- manylinux wheels: Compatible with most Linux distributions"
        echo "- macOS wheels: Compatible with macOS Intel and Apple Silicon"
        echo "- Source distributions: Universal compatibility"
        echo ""
        echo "This was a dry run - no packages were published."
        echo "To publish, run the workflow again with dry_run=false" 