name: Publish Packages

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to publish to'
        required: true
        default: 'testpypi'
        type: choice
        options:
        - testpypi
        - pypi
      dry_run:
        description: 'Dry run - only build, no publishing'
        required: false
        default: false
        type: boolean

jobs:
  build-wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-14]
    steps:
    - uses: actions/checkout@v5
    - name: Install Python
      uses: actions/setup-python@v5

    - name: Build wheels
      uses: pypa/cibuildwheel@v3.1.4
      env:
        CIBW_SOME_OPTION: value
        CIBW_BEFORE_ALL: |
          echo "=== Installing OpenSSL dependencies ==="
          if yum > /dev/null 2>&1; then
            yum update -y
            yum install -y openssl-devel
            export RUSTFLAGS="-C target-feature=-crt-static"
            export OPENSSL_DIR=/usr
            export OPENSSL_LIB_DIR=/usr/lib64
            export OPENSSL_INCLUDE_DIR=/usr/include/openssl
            export PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/lib/pkgconfig
          fi
          echo "=== Installing Rust ==="
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          source $HOME/.cargo/env
          export PATH="$HOME/.cargo/bin:$PATH"
          # Verify Rust installation
          echo "=== Rust Installation Check ==="
          cargo --version
          rustc --version
      with:
        package-dir: .
        output-dir: wheelhouse
        config-file: "{package}/pyproject.toml"

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl

  publish-python:
    name: Publish Python Package
    runs-on: ubuntu-latest
    needs: [build-wheels]
    if: >
      github.event_name == 'release' || 
      (github.event_name == 'workflow_dispatch' && (!github.event.inputs.dry_run || github.event.inputs.dry_run == 'false'))
    environment: ${{ github.event.inputs.environment || 'pypi' }}
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v5
    - name: Download all wheels
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Collect wheels
      run: |
        mkdir -p dist
        find artifacts -name "*.whl" -exec cp {} dist/ \;
        find artifacts -name "*.tar.gz" -exec cp {} dist/ \;
        ls -la dist/
    
    - name: Publish to TestPyPI
      if: github.event.inputs.environment == 'testpypi' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'testpypi')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
    
    - name: Publish to PyPI
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-rust:
    name: Publish Rust Crate
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'release' || 
      (github.event_name == 'workflow_dispatch' && (!github.event.inputs.dry_run || github.event.inputs.dry_run == 'false'))
    steps:
    - uses: actions/checkout@v5
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish