name: Publish Packages

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to publish to'
        required: true
        default: 'testpypi'
        type: choice
        options:
        - testpypi
        - pypi

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }} (${{ matrix.arch }}) for Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        arch: [amd64, arm64]
        exclude:
          # Exclude macOS ARM64 for Python 3.8 and 3.9 as they may not be supported
          - os: macos-latest
            python-version: '3.8'
            arch: arm64
          - os: macos-latest
            python-version: '3.9'
            arch: arm64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install gettext
        brew link gettext --force
        echo "PATH=/usr/local/opt/gettext/bin:$PATH" >> $GITHUB_ENV
        echo "LDFLAGS=-L/usr/local/opt/gettext/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/usr/local/opt/gettext/include" >> $GITHUB_ENV
        echo "DYLD_LIBRARY_PATH=/usr/local/opt/gettext/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Set up Python ${{ matrix.python-version }} (${{ matrix.arch }})
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.arch }}-cargo-
    
    - name: Install maturin
      run: pip install maturin[patchelf]
    
    - name: Build wheels
      run: maturin build --release --out dist --interpreter python${{ matrix.python-version }}
    
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.arch }}-py${{ matrix.python-version }}
        path: dist

  publish-python:
    name: Publish Python Package
    runs-on: ubuntu-latest
    needs: build-wheels
    environment: ${{ github.event.inputs.environment || 'pypi' }}
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all wheels
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Collect wheels
      run: |
        mkdir -p dist
        find artifacts -name "*.whl" -exec cp {} dist/ \;
        find artifacts -name "*.tar.gz" -exec cp {} dist/ \;
        ls -la dist/
    
    - name: Publish to TestPyPI
      if: github.event.inputs.environment == 'testpypi' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'testpypi')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
    
    - name: Publish to PyPI
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-rust:
    name: Publish Rust Crate
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish 