name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black ruff isort autoflake

    - name: Check Python formatting with black
      run: black --check examples tests/python

    - name: Check import sorting with isort
      run: isort --check-only examples tests/python

    - name: Lint with ruff
      run: ruff check examples tests/python

  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        arch: [amd64, arm64]
        exclude:
          # Exclude macOS ARM64 for Python 3.8 and 3.9 as they may not be supported
          - os: macos-latest
            python-version: '3.8'
            arch: arm64
          - os: macos-latest
            python-version: '3.9'
            arch: arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} (${{ matrix.arch }})
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.arch }}-cargo-

    - name: Install maturin
      run: pip install maturin[patchelf]

    - name: Create virtual environment
      run: python -m venv .venv

    - name: Activate virtual environment and install dependencies
      shell: bash
      run: |
        source .venv/bin/activate
        pip install --upgrade pip
        pip install pytest pytest-cov pytest-mock pytest-asyncio

    - name: Build Python extension
      shell: bash
      run: |
        source .venv/bin/activate
        maturin develop --release

    - name: Run Python unit tests
      shell: bash
      run: |
        source .venv/bin/activate
        cd tests/python
        pytest unit/ -v --cov=tarzi --cov-report=xml --cov-report=term
      continue-on-error: true

    - name: Run Python integration tests
      shell: bash
      run: |
        source .venv/bin/activate
        cd tests/python
        pytest integration/ -v -m "not slow"
      continue-on-error: true

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v3
      with:
        file: tests/python/coverage.xml
        flags: python
        name: python-coverage

  build-wheels:
    name: Build Python wheels on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python (${{ matrix.arch }})
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: ${{ matrix.arch }}

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install maturin
      run: pip install maturin[patchelf]

    - name: Build wheels
      run: maturin build --release --out dist

    - name: Test wheel installation
      shell: bash
      run: |
        python -m venv test_env
        source test_env/bin/activate
        wheel_file=$(ls dist/*.whl | head -1)
        pip install "$wheel_file"
        python -c "import tarzi; print('Wheel installed successfully')"

    - name: Upload wheels as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/

  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Create virtual environment and install dependencies
      shell: bash
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r docs/requirements.txt
        pip install maturin

    - name: Build Python extension for docs
      shell: bash
      run: |
        source .venv/bin/activate
        maturin develop --release

    - name: Build documentation
      shell: bash
      run: |
        source .venv/bin/activate
        cd docs
        make html

    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/_build/html/
