name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check and Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-pip

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Check code
      run: cargo check --all-targets --all-features

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Test on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            python-version: 3.11
          - os: macos-latest
            arch: x64
            python-version: 3.11
          - os: macos-latest
            arch: arm64
            python-version: 3.11
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} (${{ matrix.arch }})
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}

    - name: Required environment variables for PyO3
      run: |
        PYTHON_BIN=$(which python${{ matrix.python-version }})
        PYTHON_LIBDIR=$($PYTHON_BIN -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
        echo "PYO3_PYTHON=$PYTHON_BIN" >> $GITHUB_ENV
        echo "RUSTFLAGS=-L$PYTHON_LIBDIR -lpython${{ matrix.python-version }}" >> $GITHUB_ENV

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.arch }}-cargo-

    - name: Run unit tests
      run: cargo test --lib --all-features

    - name: Run integration tests
      run: cargo test --test '*' --all-features
      continue-on-error: true

    - name: Run doctests
      run: cargo test --doc --all-features

  build:
    name: Build Release on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    needs: [check, test]
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11 (${{ matrix.arch }})
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        architecture: ${{ matrix.arch }}

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.arch }}-cargo-

    - name: Build release binary
      run: cargo build --release --all-features

    - name: Build with Python bindings
      run: cargo build --release --features pyo3

    - name: Test binary works
      run: ./target/release/tarzi --version

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: tarzi-binary-${{ runner.os }}-${{ matrix.arch }}
        path: target/release/tarzi 